# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_principal(object):
    def setupUi(self, MainWindow_principal):
        MainWindow_principal.setObjectName("MainWindow_principal")
        MainWindow_principal.resize(640, 480)
        MainWindow_principal.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow_principal)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow_principal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuOrcamentos = QtWidgets.QMenu(self.menubar)
        self.menuOrcamentos.setObjectName("menuOrcamentos")
        self.menuCadastro = QtWidgets.QMenu(self.menubar)
        self.menuCadastro.setObjectName("menuCadastro")
        self.menuConfiguracoes = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracoes.setObjectName("menuConfiguracoes")
        self.menuRelatorios = QtWidgets.QMenu(self.menubar)
        self.menuRelatorios.setObjectName("menuRelatorios")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow_principal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_principal)
        self.statusbar.setObjectName("statusbar")
        MainWindow_principal.setStatusBar(self.statusbar)
        self.actionNovo_Orcamento = QtWidgets.QAction(MainWindow_principal)
        self.actionNovo_Orcamento.setObjectName("actionNovo_Orcamento")
        self.actionPesquisar_Orcamento = QtWidgets.QAction(MainWindow_principal)
        self.actionPesquisar_Orcamento.setObjectName("actionPesquisar_Orcamento")
        self.actionSair = QtWidgets.QAction(MainWindow_principal)
        self.actionSair.setObjectName("actionSair")
        self.actionCadastro_de_Clientes = QtWidgets.QAction(MainWindow_principal)
        self.actionCadastro_de_Clientes.setObjectName("actionCadastro_de_Clientes")
        self.actionCadastro_de_Aluminios = QtWidgets.QAction(MainWindow_principal)
        self.actionCadastro_de_Aluminios.setObjectName("actionCadastro_de_Aluminios")
        self.actionCadastro_de_Acessorios = QtWidgets.QAction(MainWindow_principal)
        self.actionCadastro_de_Acessorios.setObjectName("actionCadastro_de_Acessorios")
        self.actionCadastro_de_Vidros = QtWidgets.QAction(MainWindow_principal)
        self.actionCadastro_de_Vidros.setObjectName("actionCadastro_de_Vidros")
        self.actionCadastro_de_Produtos = QtWidgets.QAction(MainWindow_principal)
        self.actionCadastro_de_Produtos.setObjectName("actionCadastro_de_Produtos")
        self.actionSobre = QtWidgets.QAction(MainWindow_principal)
        self.actionSobre.setObjectName("actionSobre")
        self.menuOrcamentos.addAction(self.actionNovo_Orcamento)
        self.menuOrcamentos.addAction(self.actionPesquisar_Orcamento)
        self.menuOrcamentos.addSeparator()
        self.menuOrcamentos.addAction(self.actionSair)
        self.menuCadastro.addAction(self.actionCadastro_de_Clientes)
        self.menuCadastro.addAction(self.actionCadastro_de_Aluminios)
        self.menuCadastro.addAction(self.actionCadastro_de_Acessorios)
        self.menuCadastro.addAction(self.actionCadastro_de_Vidros)
        self.menuCadastro.addAction(self.actionCadastro_de_Produtos)
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuOrcamentos.menuAction())
        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuConfiguracoes.menuAction())
        self.menubar.addAction(self.menuRelatorios.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow_principal)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_principal)

    def retranslateUi(self, MainWindow_principal):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_principal.setWindowTitle(_translate("MainWindow_principal", "*** EsquadriCalc - Software para Cálculos de Esquadrias de Alumínio ***"))
        self.menuOrcamentos.setTitle(_translate("MainWindow_principal", "Orçamentos"))
        self.menuCadastro.setTitle(_translate("MainWindow_principal", "Cadastro"))
        self.menuConfiguracoes.setTitle(_translate("MainWindow_principal", "Configurações"))
        self.menuRelatorios.setTitle(_translate("MainWindow_principal", "Relatórios"))
        self.menuAjuda.setTitle(_translate("MainWindow_principal", "Ajuda"))
        self.actionNovo_Orcamento.setText(_translate("MainWindow_principal", "Novo Orçamento..."))
        self.actionPesquisar_Orcamento.setText(_translate("MainWindow_principal", "Pesquisar Orçamento"))
        self.actionSair.setText(_translate("MainWindow_principal", "Sair"))
        self.actionCadastro_de_Clientes.setText(_translate("MainWindow_principal", "Cadastro de Clientes"))
        self.actionCadastro_de_Aluminios.setText(_translate("MainWindow_principal", "Cadastro de Alumínios"))
        self.actionCadastro_de_Acessorios.setText(_translate("MainWindow_principal", "Cadastro de Acessórios"))
        self.actionCadastro_de_Vidros.setText(_translate("MainWindow_principal", "Cadastro de Vidros"))
        self.actionCadastro_de_Produtos.setText(_translate("MainWindow_principal", "Criar Produtos"))
        self.actionSobre.setText(_translate("MainWindow_principal", "Sobre..."))
